document.write("<menu class=\"menu\">");
document.write("<div class=\"sub1\">");
document.write("<button class=\"about\">About<\/button>");
document.write("<div class=\"dropdown-content\">");
document.write("<a href=\"..\/organize\/organize.html\">Organizing & scientific Committees<\/a>");
document.write("<a href=\"..\/sponsors\/sponsors.html\">Affiliations & sponsors<\/a>");
document.write("<a href=\"..\/university\/university.html\">Democritus University of Thrace<\/a>");
document.write("<\/div>");
document.write("<\/div>");
document.write("<div class=\"sub2\">");
document.write("<button class=\"mio\">Thracing on MIO 2020<\/button>");
document.write("<div class=\"dropdown-content\">");
document.write("<a href=\"..\/program\/program.html\">Programme<\/a>");
document.write("<a href=\"..\/agenda\/agenda.html\">Committees & Board Members & Agenda<\/a>");
document.write("<a href=\"..\/secretariat\/secretariat.html\">Secretariat<\/a>");
document.write("<a href=\"..\/staff\/staff.html\">Crisis team & Press team & Administrative Staff<\/a>");
document.write("<\/div>");
document.write("<\/div>");
document.write("");
document.write("<!-- <button class=\"apply\"><\/button> -->");
document.write("<div class=\"sub3\">");
document.write("<button class=\"apply\">");
document.write("<a href=\"..\/apply\/apply.html\">Apply<\/a>");
document.write("<\/button>");
document.write("<\/div>");
document.write("<div class=\"sub4\">");
document.write("<button class=\"message\">");
document.write("<a href=\"..\/crisis.pdf\">Message Room for Crisis committees<\/a>");
document.write("<\/button>");
document.write("<\/div>");
document.write("<div class=\"sub5\">");
document.write("<button class=\"guide\">Participant’s guide<\/button>");
document.write("<div class=\"dropdown-content\">");
document.write("<a href=\"..\/documentation\/documentation.html\">Documentation<\/a>");
document.write("<a href=\"..\/events\/events.html\">Social Events<\/a>");
document.write("<a href=\"..\/accomodation\/accomodation.html\">Accommodation<\/a>");
document.write("<\/div>");
document.write("<\/div>");
document.write("<div class=\"sub6\">");
document.write("<button class=\"contact\">");
document.write("<a href=\"..\/contact\/contact.html\">Contact<\/a>");
document.write("<\/button>");
document.write("<\/div>");
document.write("<div class=\"sub7\">");
document.write("<button class=\"news\">");
document.write("<a href=\"..\/news\/news.html\">News<\/a>");
document.write("<\/button>");
document.write("<\/div>");
document.write("<\/menu>");
document.write("");
document.write("<!-- MOBILE for the menu-->");
document.write("<div class=\"topnav\">");
document.write("<div id=\"mobile\">");
document.write("<div class=\"sub1\">");
document.write("<ul class=\"about\">About");
document.write("<a href=\"..\/organize\/organize.html\">Organizing & scientific Committees<\/a>");
document.write("<a href=\"..\/sponsors\/sponsors.html\">Affiliations & sponsors<\/a>");
document.write("<a href=\"..\/university\/university.html\">Democritus University of Thrace<\/a>");
document.write("<\/ul>");
document.write("<\/div>");
document.write("<div class=\"sub2\">");
document.write("<ul class=\"mio\">Thracing on MIO 2020");
document.write("<a href=\"..\/program\/program.html\">Programme<\/a>");
document.write("<a href=\"..\/agenda\/agenda.html\">Committees & Board Members & Agenda<\/a>");
document.write("<a href=\"..\/secretariat\/secretariat.html\">Secretariat<\/a>");
document.write("<a href=\"..\/staff\/staff.html\">Crisis team & Press team & Administrative Staff<\/a>");
document.write("<\/ul>");
document.write("<\/div>");
document.write("<div class=\"sub3\">");
document.write("<a href=\"..\/apply\/apply.html\">Apply<\/a>");
document.write("<\/div>");
document.write("<div class=\"sub4\">");
document.write("<a href=\"..\/crisis.pdf\">Message Room for Crisis committees<\/a>");
document.write("<\/div>");
document.write("<div class=\"sub5\">");
document.write("<ul class=\"guide\">Participant’s guide");
document.write("<a href=\"..\/documentation\/documentation.html\">Documentation<\/a>");
document.write("<a href=\"..\/events\/events.html\">Social Events<\/a>");
document.write("<a href=\"..\/accomodation\/accomodation.html\">Accommodation<\/a>");
document.write("<\/ul>");
document.write("<\/div>");
document.write("<div class=\"sub6\">");
document.write("<a class=\"contact\" href=\"..\/contact\/contact.html\">Contact<\/a>");
document.write("<\/div>");
document.write("<div class=\"sub7\">");
document.write("<a class=\"news\" href=\"..\/news\/news.html\">News<\/a>");
document.write("<\/div>");
document.write("<\/div>");
document.write("<\/div>");
